name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-gh
        environment_name: Dockergh-env
        existing_bucket_name: elasticbeanstalk-eu-central-1-123456789012
        region: eu-central-1
        version_label: 0498e2e2b9d1290f78c5a2a210614310a1450c44
        deployment_package: deploy.zip
